version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: OnlineShoppingPlatform/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./OnlineShoppingPlatform/ShoppingWeb
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
