version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: shopping-sql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopping-backend
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ShoppingDb;User Id=sa;Password=YourStrong!Passw0rd123;"
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"

volumes:
  sqlserverdata: